import os

GCP_PROJECT_ID = os.getenv("PROJECT_ID")
DATASET_ID = os.getenv("DATASET_ID")
TABLE_ID = os.getenv("TABLE_ID")
SELF_IDS_LOOKER_STUDIO = os.getenv("SELF_IDS_LOOKER_STUDIO")

LOW_COUNT_GENDER = 5
